apiVersion: batch/v1
kind: CronJob
metadata:
  name: mycronjob
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template: 
       metadata:
        labels:
         app: myjob
       spec:
         restartPolicy: OnFailure
         containers:
           - name: main
             image: luksa/batch-job
