apiVersion: v1
kind: ReplicationController
metadata:
 name: replicapod
spec:
 replicas: 3
 template:
  metadata:
   labels:
    app: dev
  spec:
   containers: 
    - image: nginx
      name: nginxcontainer
      ports: 
       - containerPort: 80

